  version: '3'
  services:
    r1:
      build: redis/.
      ports:
        - "6379:6379"
      volumes:
        - rd1:/data/bases
      environment:
        - 'CLUSTER_ANNOUNCE_PORT=6379'
        - 'CLUSTER_ANNOUNCE_IP=192.168.0.183'

  volumes:
    rd1:
      driver: local