  version: '3'
  services:
    r1:
      build: redis/.
      user: redis:redis
#      image: "redis"
      ports:
        - "6379:6379"
      volumes:
        - rd1:/data/bases
      environment:
        - "CLUSTER_ANNOUNCE_PORT=6379"
        - "CLUSTER_ANNOUNCE_IP=${EXTERNAL_IP}"

  volumes:
    rd1:
      driver: local